//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.11 at 09:09:43 PM IST 
//


package corp.cencosud.dscl_omnichannel_int2336.onlinestockoutputmessage;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


public class Stock_online_resp {

    protected BigInteger cod_resp;
    protected String msg_resp;
    protected String desc_art;
    protected String desc_local;
    protected BigInteger sku;
    protected BigInteger ean;
    public List<Stock_online_resp.Stock> stock;



    public void setStock(List<Stock_online_resp.Stock> stock) {
        this.stock = stock;
    }

    /**
     * Gets the value of the cod_resp property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCod_resp() {
        return cod_resp;
    }

    /**
     * Sets the value of the cod_resp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCod_resp(BigInteger value) {
        this.cod_resp = value;
    }

    /**
     * Gets the value of the msg_resp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsg_resp() {
        return msg_resp;
    }

    /**
     * Sets the value of the msg_resp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsg_resp(String value) {
        this.msg_resp = value;
    }

    /**
     * Gets the value of the desc_art property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc_art() {
        return desc_art;
    }

    /**
     * Sets the value of the desc_art property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc_art(String value) {
        this.desc_art = value;
    }

    /**
     * Gets the value of the desc_local property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc_local() {
        return desc_local;
    }

    /**
     * Sets the value of the desc_local property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc_local(String value) {
        this.desc_local = value;
    }

    /**
     * Gets the value of the sku property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSku() {
        return sku;
    }

    /**
     * Sets the value of the sku property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSku(BigInteger value) {
        this.sku = value;
    }

    /**
     * Gets the value of the ean property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEan() {
        return ean;
    }

    /**
     * Sets the value of the ean property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEan(BigInteger value) {
        this.ean = value;
    }

    /**
     * Gets the value of the stock property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stock property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStock().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Stock_online_resp.Stock }
     * 
     * 
     */
    public List<Stock_online_resp.Stock> getStock() {
        if (stock == null) {
            stock = new ArrayList<Stock_online_resp.Stock>();
        }
        return this.stock;
    }

    public static class Stock {

        protected BigInteger sku;
        protected BigInteger stock_ant;
        protected BigInteger ventas;
        protected BigInteger nota_credito;
        protected BigInteger stock_act;
        protected BigInteger mes_antiguedad;
        protected String talla;
        protected String color;

        /**
         * Gets the value of the sku property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getSku() {
            return sku;
        }

        /**
         * Sets the value of the sku property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setSku(BigInteger value) {
            this.sku = value;
        }

        /**
         * Gets the value of the stock_ant property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getStock_ant() {
            return stock_ant;
        }

        /**
         * Sets the value of the stock_ant property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setStock_ant(BigInteger value) {
            this.stock_ant = value;
        }

        /**
         * Gets the value of the ventas property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getVentas() {
            return ventas;
        }

        /**
         * Sets the value of the ventas property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setVentas(BigInteger value) {
            this.ventas = value;
        }

        /**
         * Gets the value of the nota_credito property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNota_credito() {
            return nota_credito;
        }

        /**
         * Sets the value of the nota_credito property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNota_credito(BigInteger value) {
            this.nota_credito = value;
        }

        /**
         * Gets the value of the stock_act property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getStock_act() {
            return stock_act;
        }

        /**
         * Sets the value of the stock_act property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setStock_act(BigInteger value) {
            this.stock_act = value;
        }

        /**
         * Gets the value of the mes_antiguedad property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getMes_antiguedad() {
            return mes_antiguedad;
        }

        /**
         * Sets the value of the mes_antiguedad property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setMes_antiguedad(BigInteger value) {
            this.mes_antiguedad = value;
        }

        /**
         * Gets the value of the talla property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTalla() {
            return talla;
        }

        /**
         * Sets the value of the talla property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTalla(String value) {
            this.talla = value;
        }

        /**
         * Gets the value of the color property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getColor() {
            return color;
        }

        /**
         * Sets the value of the color property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setColor(String value) {
            this.color = value;
        }

    }

}
